[project]
name = "notorious-r-a-g"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "baml-py>=0.60.0",
    "reflex>=0.6.2.post1",
]
