[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "composio-llamaindex>=0.5.11",
    "fastapi>=0.115.0",
    "python-dotenv>=1.0.1",
]
